### ISSUE TITLE
Tags field in "Podcast" not working 

### ISSUE THREAD

**Issue by hkpmcgregor** [sfu-dhil/amplify#21]
**Describe the bug**
The tag field in the Podcast category has a +/- button beside it; the + appears to do nothing, and the - causes the entire field to disappear. 

**Expected behavior**
I assume, based on the +/- button, that a new field is supposed to appear to enter additional keywords? 

**Screenshots**
<img width="1169" alt="Screen Shot 2020-10-21 at 3 32 18 PM" src="https://user-images.githubusercontent.com/72821163/96794235-b06d6d80-13b2-11eb-99cc-6e38d7e158d6.png">

**Desktop (please complete the following information):**
 - iOS
 - Chrome

**Comment by ubermichael** [comment]
LOL that #25 took out a lot of functionality!
