### ISSUE TITLE
Links field on "New Person" page not appearing

### ISSUE THREAD

**Issue by hkpmcgregor** [sfu-dhil/amplify#22]
**Describe the bug**
When adding a new person (from the "Season" page), the Link field appears as a title but there is no field to fill. Because the field is required (has a red asterisk) but cannot be filled, the New Person entry cannot be saved. 

**Expected behavior**
The links field should be fillable and the page should be saveable! 

**Screenshots**
<img width="1239" alt="Screen Shot 2020-10-21 at 3 35 37 PM" src="https://user-images.githubusercontent.com/72821163/96794613-5c16bd80-13b3-11eb-8ebd-0d92f008d6da.png">

**Comment by ubermichael** [comment]
Well, that's neat. The thing that fixed #25 will also fix this! The javascript was trying to turn the links field into a subject autocomplete thing, but the autocomplete thing isn't enabled for people and then it just quit.
