### ISSUE TITLE
Error when trying to edit Episode entry 

### ISSUE THREAD

**Issue by hkpmcgregor** [sfu-dhil/amplify#23]
**Describe the bug**
After trying to edit the entry for episode 1 of Secret Feminist Agenda I received an error (details in screenshot). I had specifically tried to delete the Person field. 

**Screenshots**
<img width="1222" alt="Screen Shot 2020-10-21 at 3 49 57 PM" src="https://user-images.githubusercontent.com/72821163/96798198-3b4f6780-13b5-11eb-9d55-e25dc2131515.png">

**Comment by ubermichael** [comment]
This happened because the Person field was blank. To remove a person from an episode you need to use the minus button to remove the person and role.
