### ISSUE TITLE
Contributor Institution outside Canada? 

### ISSUE THREAD

**Issue by hkpmcgregor** [sfu-dhil/amplify#24]
Currently contributor institutions are only available for contributors within Canada. Consider expanding so that international podcast guests can also have their institutions listed?

**Comment by ubermichael** [comment]
You can add new institutions as you need. Select Institutions in the Browse menu, then use the New button to create a new institution.

**Comment by hkpmcgregor** [comment]
Currently the new institution form has two fields, both required: Province and Institution. We'd have to change the Province field if we wanted to include international institutions.


Hannah McGregor
Assistant Professor & Graduate Program Chair | Publishing

Pronouns: she/her
Simon Fraser University | Harbour Centre

515 West Hastings St., Vancouver, B.C. V6B 5K3
hannahmcgregor.com<https://hannahmcgregor.com/> | @hkpmcgregor<https://twitter.com/hkpmcgregor>

[1572290631382]
________________________________

**Comment by ubermichael** [comment]
Ok. How about dropping Province all together and adding Country instead?

**Comment by hkpmcgregor** [comment]
I think that makes sense, unless there's some reason I'm not thinking of that we need province metadata for Canadian institutions...


Hannah McGregor
Assistant Professor & Graduate Program Chair | Publishing

Pronouns: she/her
Simon Fraser University | Harbour Centre

515 West Hastings St., Vancouver, B.C. V6B 5K3
hannahmcgregor.com<https://hannahmcgregor.com/> | @hkpmcgregor<https://twitter.com/hkpmcgregor>

[1572290631382]
________________________________
