### ISSUE TITLE
Tags and Subject field in New Episode form appear to have the same function 

### ISSUE THREAD

**Issue by hkpmcgregor** [sfu-dhil/amplify#25]
**Describe the bug**
The Tags and Subject fields in the New Episode form appear to auto-complete from the same available set of categories. It's still not totally clear to me what the Tags field is for!

**Comment by ubermichael** [comment]
That's absolutely not how it should work. Tags should be free text - you can choose anything you want for them. Subject is the OCLC cataloging subject headings.
